### ISSUE TITLE
GFCI socket tripping while charging

### ISSUE THREAD

**Issue by abtinling** [directedmachines/customer-support#15] opened 2021-07-07 17:26 UTC
When plugging in to an outdoor GFCI outlet on our shed, the charger periodically trips the GFCI. Not certain of the cause. Maybe the GFCI is just rated for a lower amp draw than the charger wants. But also there is a "Notice Polarity!" message on battery charger when plugged in. Not sure if this indicates an issue or not.

![image](https://user-images.githubusercontent.com/84051775/124803236-b473f800-df0d-11eb-971e-2ff8dc320a4b.png)

**Comment by georgechrysanthakopoulos** [comment] 2021-07-07 17:58
@abtinling Our charger should nout pull more than 13A from your 110V circuit. Can you please confirm, add a picture to this issue, when it is charging to confirm the max current? If we are below 15A then the issue is with your home circuit , breaker. We have seen low voltage form older home/barn circuits, which causes current to jump above 15A.

**Comment by georgechrysanthakopoulos** [comment] 2021-07-19 23:00
@abtinling I am closing this, charger is measuring to 13A peak, so everything seems ok. "check polarity" warning is seen on all of them with no adverse effects. If you have a AC multi meter (clamp amp meter) you can verify at your place. I suspect you are at low volts (below 110V) which is causing the home breaker to trip due to the increased draw to compensate

**Closed by georgechrysanthakopoulos** 2021-07-19 23:00 UTC
Labels: wontfix
